// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRbED7KR2S8Ws3yh1GQ7sI6mpyE-1ec0',
    appId: '1:382282457574:web:d211da161f04312f87b627',
    messagingSenderId: '382282457574',
    projectId: 'adidas-e-commerce',
    authDomain: 'adidas-e-commerce.firebaseapp.com',
    storageBucket: 'adidas-e-commerce.appspot.com',
    measurementId: 'G-46VN2XYRY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo7YTEHdsEjihzmwTEe2RZwmIswNT2tcQ',
    appId: '1:382282457574:android:e04a4b0c79f5238787b627',
    messagingSenderId: '382282457574',
    projectId: 'adidas-e-commerce',
    storageBucket: 'adidas-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxA7IM1cOqB0dd35jslxPaMvMI-sj2e8',
    appId: '1:382282457574:ios:55767749a00cc27f87b627',
    messagingSenderId: '382282457574',
    projectId: 'adidas-e-commerce',
    storageBucket: 'adidas-e-commerce.appspot.com',
    iosClientId: '382282457574-n1s93tpm4nagdfib8au5p80cocs0i0ss.apps.googleusercontent.com',
    iosBundleId: 'lk.ce.adidas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxA7IM1cOqB0dd35jslxPaMvMI-sj2e8',
    appId: '1:382282457574:ios:f31fa3d4c2d7941387b627',
    messagingSenderId: '382282457574',
    projectId: 'adidas-e-commerce',
    storageBucket: 'adidas-e-commerce.appspot.com',
    iosClientId: '382282457574-qf7ver85paagtsanr9rj4janfm845562.apps.googleusercontent.com',
    iosBundleId: 'lk.ce.adidas.RunnerTests',
  );
}
